### ISSUE TITLE
/etc/lxc/lxc-openvswitch : permission denied with lxc-create

### ISSUE THREAD

**Issue by kripskroll** [knorrie/network-examples#11]
Hi,

I follow the lab creation and I'm blocked because I can't start the container with this command :
lxcbird:/var/lib/lxc/birdbase 0-# lxc-start -d -n birdbase

With logpriority at DEBUG level, here is the output log file : 

lxc-start birdbase 20210305165213.101 INFO     lsm - lsm/lsm.c:lsm_init:50 - LSM security driver AppArmor
lxc-start birdbase 20210305165213.101 DEBUG    terminal - terminal.c:lxc_terminal_peer_default:714 - Using terminal "/dev/tty" as proxy
lxc-start birdbase 20210305165213.101 DEBUG    terminal - terminal.c:lxc_terminal_signal_init:192 - Created signal fd 9
lxc-start birdbase 20210305165213.101 DEBUG    terminal - terminal.c:lxc_terminal_winsz:90 - Set window size to 145 columns and 33 rows
lxc-start birdbase 20210305165213.161 INFO     start - start.c:lxc_init:904 - Container "birdbase" is initialized
lxc-start birdbase 20210305165213.161 INFO     conf - conf.c:run_script_argv:356 - Executing script "/etc/lxc/lxc-openvswitch" for container "birdbase", config section "net"
**lxc-start birdbase 20210305165213.162 DEBUG    conf - conf.c:run_buffer:326 - Script exec /etc/lxc/lxc-openvswitch birdbase net up veth  birdbase.10 with output: sh: 1: exec: /etc/lxc/lxc-openvswitch: Permission denied**

lxc-start birdbase 20210305165213.162 ERROR    conf - conf.c:run_buffer:335 - Script exited with status 126
lxc-start birdbase 20210305165213.195 ERROR    network - network.c:lxc_create_network_priv:2457 - Failed to create network device
lxc-start birdbase 20210305165213.195 ERROR    start - start.c:lxc_spawn:1638 - Failed to create the network
lxc-start birdbase 20210305165213.195 ERROR    start - start.c:__lxc_start:1951 - Failed to spawn container "birdbase"
lxc-start birdbase 20210305165213.256 ERROR    lxc_start - tools/lxc_start.c:main:330 - The container failed to start
lxc-start birdbase 20210305165213.256 ERROR    lxc_start - tools/lxc_start.c:main:336 - Additional information can be obtained by setting the --logfile and --logpriority options

I tried to google around with similar errors when using script after network init but I can't find anything related
Any idea would be really helpful

Thanks in advance

**Comment by knorrie** [comment]
Hi!

The little helper script file needs to have the executable 'permission' bit set.

chmod +x /etc/lxc/lxc-openvswitch

Hans

P.S. Most likely it's this. Otherwise we'll see about it again tomorrow. Have fun.

**Comment by kripskroll** [comment]
Perfect. Thank you very much :)
