### ISSUE TITLE
Create copy of birdbase

### ISSUE THREAD

**Issue by kripskroll** [knorrie/network-examples#12]
Hi,

When creating the copy of the birdbase container as explained in Basic Network, it is not mentionned that the files _interfaces_ and _firewalls_ in folder _/etc/network/_ needs to take place in the _delta0_ folder of the 2 new container sparrow and weaver.
It is also needed to create folder _network_ : 
`
root@debian10:/var/lib/lxc# mkdir sparrow/delta0/etc/network
root@debian10:/var/lib/lxc# vi sparrow/delta0/etc/network/interfaces
root@debian10:/var/lib/lxc# vi sparrow/delta0/etc/network/firewall
`
It would be really helpful for newbies like me :)

Thanks a lot

**Comment by knorrie** [comment]
Hi again, I had never seen this 'delta0', so I went to look what it is.

Apparently, delta0 appears when using lxc with the overlayfs variant of cloning containers. (E.g. https://the.binbashtheory.com/using-overlayfs-with-lxc/ ). Since I have always been using btrfs snapshots, I had never seen it. For me, it's always just 'rootfs' for everything.

I'm not sure yet what to do about this... Since I recommend using the latest stable Debian release, it's probably best to follow whatever are the defaults in there.

What exact options did you use for the lxc-create step?

**Comment by kripskroll** [comment]
Hi,

I´m using latest Debian 10 release from debian.org
BUT I´m not using btrfs because I had an error when I tried to use it. So I went to "-B best" flag : 
```
root@debian10:/var/lib/lxc# MIRROR=http://ftp.fr.debian.org/debian lxc-create -t debian -B best -n birdbase -- -r buster
```
Here is the error I had when I tried to use btrfs : 
```
root@debian10:/var/lib/lxc# MIRROR=http://ftp.fr.debian.org/debian lxc-create -t debian -B btrfs -n birdbase -- -r buster
lxc-create: birdbase: storage/btrfs.c: btrfs_create: 952 Inappropriate ioctl for device - Failed to create btrfs subvolume "/var/lib/lxc/birdbase/rootfs"
lxc-create: birdbase: lxccontainer.c: do_storage_create: 1272 Failed to create "btrfs" storage
lxc-create: birdbase: lxccontainer.c: do_lxcapi_create: 1869 Failed to create btrfs storage for birdbase
lxc-create: birdbase: tools/lxc_create.c: main: 327 Failed to create container birdbase
```
In fact, not a big issue. My understanding is that lxc-copy do not really copy the full rootfs from the base container. It uses the base rootfs except for files present in delta0 that are used in place of the original one. Seems to be efficient for the volume of storage. Not sure I´m right.

So in order to  keep using your script from github, I just move them from rootfs to delta0 : 
```
root@debian10:~/network-examples/ospf-intro/lxc# for router in 2 5 6; do mv R$router/rootfs R$router/delta0 ; sleep 2; done
root@debian10:~/network-examples/ospf-intro/lxc# cd /var/lib/lxc
root@debian10:~/network-examples/ospf-intro/lxc# cp ~/network-examples/ospf-intro/lxc/[RH]* . -r
```
At the end , everything is working fine. 
Thanks a lot
--Kripskroll

**Comment by knorrie** [comment]
Ok, very good. Yes, you can only use btrfs snapshots on an actual btrfs file system. I'll add a remark that just hints at the possibility that there can be some minor differences when using different storage options than the tutorial uses as example.
