### ISSUE TITLE
Setting up a lab environment - nameserver setup is not in /etc/network/interfaces

### ISSUE THREAD

**Issue by jprukner** [knorrie/network-examples#6]
I spent some time figuring out why I can not resolve domain names. It might be obvious for everybody else that it needs to be set up in /etc/resolv.conf. So I don't know if it should be mentioned or not. Just letting you know. @knorrie

**Comment by knorrie** [comment]
Interesting. When I created the initial container, the resolv.conf was copied from the "host" os, so I didn't have to change that manually.

**Comment by knorrie** [comment]
Can you confirm that your lxc-create does or does not figure out what to put in resolv.conf, and if it does not, do you have a reproduction scenario, listing specific versions of all software used?

**Comment by jprukner** [comment]
Actually, it was not working on lxc host because I overwritten the default interface configuration with your configuration so everything is lined up with your address spaces. But it also made /etc/resolv.conf empty because there is no name server configuration in /etc/network/interfaces. I used fresh debian VM. It was a stupid mistake.

**Comment by knorrie** [comment]
Ok, no problem. :-)

Thanks for trying the tutorial. I hope it's useful for you.
