### ISSUE TITLE
Upgrade to Debian 10 / LXC 3.x for Hacktoberfest

### ISSUE THREAD

**Issue by toloveru** [knorrie/network-examples#9]
Hello,

Thanks for making this repo! I've learned a lot about BIRD following it so far. The tutorials still seem to be geared at Debian 9 and LXC 2.x however. I've already done the upgrade in my own infrastructure and as part of the network examples locally. It seems like many steps will have to be taken to fully do the upgrade, so that could easily make for 4 pull requests.

Specifically, I'd like to update these components:
- The documentation itself
- The necessary LXC keys and other such configuration
- The scripts used along the tutorial.(such as fixnetwork.sh)

In order for the pull requests to qualify, apparently the hacktoberfest tag would need to be added to the repo. This would probably attract even more spam from the audience of that particular YouTuber though.. apparently it's necessary but perhaps it's worth waiting with that until that spam settles down first? Short of my local stuff being already upgraded, all the repository updates also still have to be done anyway.

**Comment by knorrie** [comment]
Hi,

Meanwhile, this work has been done by other people. I have never seen any of those actual pull requests you were talking about.

Closing now.

Hans
